name: Auto Approve PRs

permissions:
  pull-requests: write
  contents: read

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'jsredmond'
    steps:
      - name: Auto-approve pull request
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
